package com.task.podcast.feature.home.domain.entity

data class ContentEntity(
    val podcastId: String? = null,
    val episodeId: String? = null,
    val audiobookId: String? = null,
    val articleId: String? = null,
    val name: String,
    val authorName: String? = null,
    val description: String,
    val avatarUrl: String,
    val episodeCount: String? = null,
    val duration: Int,
    val language: String? = null,
    val priority: String? = null,
    val popularityScore: String? = null,
    val score: String,
    val seasonNumber: Int? = null,
    val episodeType: String? = null,
    val podcastName: String? = null,
    val number: Int? = null,
    val separatedAudioUrl: String? = null,
    val audioUrl: String? = null,
    val releaseDate: String? = null,
    val paidIsEarlyAccess: Boolean? = null,
    val paidIsNowEarlyAccess: Boolean? = null,
    val paidIsExclusive: Boolean? = null,
    val paidTranscriptUrl: String? = null,
    val freeTranscriptUrl: String? = null,
    val paidIsExclusivePartially: Boolean? = null,
    val paidExclusiveStartTime: Int? = null,
    val paidEarlyAccessDate: String? = null,
    val paidEarlyAccessAudioUrl: String? = null,
    val paidExclusivityType: String? = null
)